# Generated by Django 4.2.9 on 2024-03-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StreamPage",
            new_name="PbaStreamPage",
        ),
        migrations.RenameModel(
            old_name="WelcomeStreamPage",
            new_name="WelcomePbaStreamPage",
        ),
    ]
