# Generated by Django 4.2.11 on 2024-03-29 18:32

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_rename_streampage_pbastreampage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pbastreampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Left"),
                                            ("center", "Center"),
                                            ("right", "Right"),
                                        ]
                                    ),
                                ),
                                ("paragraph", wagtail.blocks.RichTextBlock()),
                            ],
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ],
                        ),
                    ),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                    ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                    (
                        "typed_table_block",
                        wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                            [
                                ("rich_text", wagtail.blocks.RichTextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("html", wagtail.blocks.RawHTMLBlock()),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
